# NAME: Andrew Grove
# EMAIL: koeswantoandrew@gmail.com
# ID: 304785991

default:
	gcc -o lab1a -g lab1a.c 2> "/dev/null"

clean:
	rm -f lab1a *.tar.gz

dist: default
	tar -czvf lab1a-304785991.tar.gz Makefile lab1a.c README
