# NAME: Andrew Grove
# EMAIL: koeswantoandrew@gmail.com
# ID: 304785991

default:
	gcc -w -Wall -Wextra -o lab2_list SortedList.c lab2_list.c -pthread
	gcc -w -Wall -Wextra -o lab2_list2 SortedList.c lab2_list2.c -pthread
